version: '3'
services:
  db:
    image: postgres:12
    command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:2.x-dev
    volumes:
      - './www:/opt/drupal'
    environment:
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready

  test-runner:
    depends_on:
      - www
    image: farmos/farmos:2.x
    entrypoint: /bin/bash
    # Wait both for the dev farmOS container to have finished copying its files and for postgres to be online before launching the test-runner docker-entrypoint.sh
    # this ensures that the test-runner-container-fs-ready file can be used to wait until everything is ready to run the tests
    command: -c 'until [ -f /opt/drupal/www-container-fs-ready ]; do sleep 0.1; done && while !</dev/tcp/db/5432; do sleep 0.1; done && exec docker-entrypoint.sh apache2-foreground'
    volumes:
      - './www:/opt/drupal'
    environment:
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/test-runner-container-fs-ready
